channels:
  - anaconda
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - connexion[swagger-ui]
  - html2text
  - keras-gpu=2.3.1
  - matplotlib
  - numpy
  - pandas
  - rdkit
  - scikit-learn=1.0
  - tensorflow-gpu=1.15.0
  - mongoengine
  - jinja2
  - pika
  - docker-py
  - XlsxWriter
  - seaborn
  - gevent
  - tornado
  - pip
  - pip:
      - epam.indigo==1.4.3
      - connexion[swagger-ui]
      - flask-cors
